---
date: 2018-01-03T11:38:42-04:00
subtitle: ""
tags: []
type: "post"
title: "Effect of landing page and upgrade modal intervention on Awesome MRR"
---



<div id="tldr" class="section level3">
<h3>TL;DR</h3>
<ul>
<li><p>Changes to the app and landing pages have led to a large (30%) and significant increase in Awesome trial starts.</p></li>
<li><p>There are indications of a positive effect on Awesome MRR, but the probability of a true effect is inconclusive.</p></li>
<li><p>The free plan experiment was a major confounding factor that did increase Awesome MRR.</p></li>
</ul>
</div>
<div id="background" class="section level3">
<h3>Background</h3>
<p>Back in September, Buffer experienced a period of relatively low <a href="https://github.com/bufferapp/buffer-analysis/blob/master/deliverables/september_mrr_analysis.md">MRR growth</a>. This was especially impactful for the Awesome plans, which saw a sharp and distinct decrease in growth.</p>
<p>There were several factors that could have contributed to this change: landing page changes, product changes, churn, and bugs all conspired to create a batch effect that slowed growth for Awesome subscriptions. After a lot of analysis and many conversations, we <a href="https://paper.dropbox.com/doc/Meeting-notes-Awesome-trial-decline-Landing-page-changes-cR1SIYptglsspqVOnN0He">took action</a> on October 11 by <a href="https://buffer.slack.com/archives/C14F676AZ/p1507709680000379?thread_ts=1507624638.000063&amp;cid=C14F676AZ">fixing a bug</a> that prevented the Awesome upgrade modal from appearing and on October 13 by reverting some changes made to the landing page.</p>
<p>It has been a few months since we’ve made these changes, so we can try to measure the impact that these changes have made so far on Awesome trials and Awesome MRR. In order to estimate the effects, we’ll use an R package written by Google engineers for causal inference called <code>CausalImpact</code>. A controlled experiment is the gold standard for estimating effect sizes, but we don’t have that here – we effectively put everyone in the experiment group. Sometimes that is necessary! There are still ways to estimate effect sizes.</p>
<p>The idea is this: given a response time series (e.g. trials, revenue) and a set of control time series (e.g. clicks in non-affected markets or clicks on other sites), the package constructs a Bayesian structural time-series model. This model is then used to try and predict the counterfactual, i.e. how the response metric would have evolved after the intervention if the intervention had never occurred.</p>
<p>The model assumes that the time series of the treated unit can be explained in terms of a set of covariates which were themselves not affected by the intervention whose causal effect we are interested in. We’ll use time and business trials as the covariates.</p>
<p>Let’s give it a shot!</p>
</div>
<div id="awesome-trials" class="section level3">
<h3>Awesome trials</h3>
<p>Before we look at MRR, let’s look at the number of Awesome trials started. I believe these are more directly under our control - we have a greater influence on the number of trial starts than we do over the number of people that subscribe or churn.</p>
<p>We’ll use the data in <a href="https://looker.buffer.com/looks/4171">this Look</a> and import it using the <code>buffer</code> package.</p>
<pre class="r"><code># import data from Looker
# trials &lt;- get_look(4171)</code></pre>
<p>Let’s do a bit of cleanup now.</p>
<pre class="r"><code># rename columns
colnames(trials) &lt;- c(&#39;start_date&#39;, &#39;awesome_trials&#39;, &#39;business_trials&#39;)

# set dates as date type
trials$start_date &lt;- as.Date(trials$start_date, format = &#39;%Y-%m-%d&#39;)</code></pre>
<p>Great, let’s plot these values out.</p>
<p><img src="/blog/awesome-causal-impact_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Immediately we can see a large “bump” in the number of Awesome trials around the end of October. This is likely due to an experiment that we ran to measure the effects of a simplified and more-limited free plan. This is a major confounding variable that may also effect revenue, but we may be able to control for it.</p>
<pre class="r"><code># load zoo package
library(zoo)

# create time series object
trials_ts &lt;- zoo(dplyr::select(trials, awesome_trials:business_trials), trials$start_date)

# specify the pre and post periods
pre.period &lt;- as.Date(c(&quot;2017-07-04&quot;, &quot;2017-10-10&quot;))
post.period &lt;- as.Date(c(&quot;2017-10-11&quot;, &quot;2017-10-27&quot;))</code></pre>
<p>We defined the post-intervention period to be from October 11, when the changes were made, to October 27. The reason that I cut it off was that the free plan experiment began around October 26, and this confounds the data. We try to limit this effect somewhat here. To perform inference, we run the analysis using the <code>CausalImpact</code> command.</p>
<pre class="r"><code># run analysis
impact &lt;- CausalImpact(trials_ts, pre.period, post.period, model.args = list(niter = 5000, nseasons = 7))</code></pre>
<p>Let’s plot the outcome of the model.</p>
<pre class="r"><code># plot results
plot(impact)</code></pre>
<p><img src="/blog/awesome-causal-impact_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The resulting plot is quite interesting. The top panel in the graph shows the counterfactual as a dotted line and blue confidence interval – this is the estimate of what trials would have been <em>without an intervention</em>. The solid black line shows the number of Awesome trials that actually were started.</p>
<p>The middle panel shows the point estimate of the effect of the intervention on each day. We can see that the point estimate of the effect is around 25-100 extra trials <em>each day</em>.</p>
<p>The bottom panel visualizes the cumulative effect that the intervention had on Awesome trial starts. As of October 31, the cumulative effect is around 1000 extra trial starts. Wow!</p>
<p>How can we determine if this effect is statistically significant? That is the core question, since we don’t have a controlled experiment here.</p>
<pre class="r"><code># get summary
summary(impact)</code></pre>
<pre><code>## Posterior inference {CausalImpact}
## 
##                          Average      Cumulative  
## Actual                   217          3689        
## Prediction (s.d.)        167 (4.9)    2839 (83.6) 
## 95% CI                   [157, 176]   [2671, 2999]
##                                                   
## Absolute effect (s.d.)   50 (4.9)     850 (83.6)  
## 95% CI                   [41, 60]     [690, 1018] 
##                                                   
## Relative effect (s.d.)   30% (2.9%)   30% (2.9%)  
## 95% CI                   [24%, 36%]   [24%, 36%]  
## 
## Posterior tail-area probability p:   2e-04
## Posterior prob. of a causal effect:  99.97993%
## 
## For more details, type: summary(impact, &quot;report&quot;)</code></pre>
<p>This summary tells us that we’ve seen an average of 217 awesome trials since the action was taken. The predicted average, based on previous months worth of data, would have been 166. The relative effect was a 30% increase in awesome trial starts – the 95% confidence interval for this effect size is [24%, 36%]. That’s a big effect!</p>
<p>The probability of a true causal effect is very high (99.98%), which makes sense given what we saw in the graphs. Nice!</p>
</div>
<div id="awesome-mrr" class="section level3">
<h3>Awesome MRR</h3>
<p>I have a hunch that this effect will be harder to detect, if it does exist. We’ll use the same approach as we did with trials, excepct this time we’ll look at Awesome MRR in <a href="https://looker.buffer.com/looks/4173">this look</a>.</p>
<pre class="r"><code># collect data
mrr &lt;- get_look(4173)

# remove first row
mrr &lt;- mrr[-1, ]

# rename columns
colnames(mrr) &lt;- c(&#39;date&#39;, &#39;awesome_mrr&#39;, &#39;business_mrr&#39;)

# set numeric values
mrr$awesome_mrr &lt;- as.numeric(as.character(mrr$awesome_mrr))
mrr$business_mrr &lt;- as.numeric(as.character(mrr$business_mrr))

# set as date
mrr$date &lt;- as.Date(mrr$date, format = &#39;%Y-%m-%d&#39;)</code></pre>
<p>Let’s plot the values.</p>
<p><img src="/blog/awesome-causal-impact_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Now let’s try to see if we’ve been able to make any impact on Awesome MRR.</p>
<pre class="r"><code># create time series object
mrr_ts &lt;- zoo(dplyr::select(mrr, awesome_mrr), mrr$date)

# specify the pre and post periods
pre.period &lt;- as.Date(c(&quot;2017-07-05&quot;, &quot;2017-10-10&quot;))
post.period &lt;- as.Date(c(&quot;2017-10-11&quot;, &quot;2017-10-31&quot;))

# run analysis
mrr_impact &lt;- CausalImpact(mrr_ts, pre.period, post.period, model.args = list(niter = 5000, nseasons = 7))

# plot impact
plot(mrr_impact)</code></pre>
<p><img src="/blog/awesome-causal-impact_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Please ignore the <code>cumulative</code> panel, as it is not relevant to us here (MRR is already an aggregation and we don’t sum it every day).</p>
<p>The <code>original</code> panel shows the counterfactual, as well as the confidence bands, as the dotted line and blue ribbon. The solid black line is the actual MRR amounts we’ve seen. We can see here that the observed values (the solid black line) are within the bounds of the confidence interval during the time window we have selected. However, we can see that there are indications of a positive effect on Awesome MRR during this timeframe.</p>
<p>If we look beyond the effect period, we can see that the free plan experiment does indeed seem to have a positive effect on Awesome MRR.</p>
<pre class="r"><code># summarise model
summary(mrr_impact)</code></pre>
<pre><code>## Posterior inference {CausalImpact}
## 
##                          Average              Cumulative        
## Actual                   5.8e+05              1.2e+07           
## Prediction (s.d.)        5.8e+05 (596)        1.2e+07 (12506)   
## 95% CI                   [5.8e+05, 5.8e+05]   [1.2e+07, 1.2e+07]
##                                                                 
## Absolute effect (s.d.)   486 (596)            10202 (12506)     
## 95% CI                   [-681, 1636]         [-14298, 34350]   
##                                                                 
## Relative effect (s.d.)   0.083% (0.1%)        0.083% (0.1%)     
## 95% CI                   [-0.12%, 0.28%]      [-0.12%, 0.28%]   
## 
## Posterior tail-area probability p:   0.20628
## Posterior prob. of a causal effect:  79%
## 
## For more details, type: summary(impact, &quot;report&quot;)</code></pre>
<p>The summary confirms that we have not seen a sufficiently large enough effect on Awesome MRR to attribute it directly to the changes made to landing pages.</p>
</div>
